development: &defaults
  # Site title and short name (latter is optional).
  site_name: Edmonton Free Library
  site_name_short: e.f.l.
  # Where is this free library located?
  site_region: Edmonton
  site_region_long: the Edmonton capital region
  # CSS Style file, a file app/assets/stylesheets or a full URL.
  css_style: andreas06.css
  # Set this to false if you can't store images on your server (Heroku).
  fetch_covers: true
  # Some tags are not acceptable.
  TAG_BLACKLIST: [general, Amazon.com, fuck, shit, crap]
  # Key for retrieving book info using the ISBNDB API.
  ISBNDB_KEY: PJ6X926W
  # Whether to ask members for phone number and send sms on loan request
  use_sms: true
  # Mail configuration
  mail_from: admin@freelibrary.ca
  mail_url_options:
    host: freelibrary.ca

production:
  <<: *defaults

test:
  <<: *defaults
